name: Deploy Users Service
on:
  push:
    branches:
      - main
#    paths:
#      - 'microservice-users/**'
  pull_request:
    branches:
      - main
#    paths:
#      - 'microservice-users/**'
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      DB_TYPE: sqlite
      DB_DATABASE: mydatabase.sqlite
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          cd microservice-users
          npm install
      - name: Test
        run: |
          cd microservice-users
          npm run test:e2e-cov
  deploy:
    needs:
      - test
    name: Deploy
    uses: ./.github/workflows/deploy-microservice-workflow.yaml
    with:
      service: 'microservice-users'
      region: 'us-central1'
      source: './microservice-users'
    secrets:
      wif_provider: ${{ secrets.WIF_PROVIDER }}
      wif_service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}