name: Deploy Users Service
on:
  push:
    branches:
      - main
#    paths:
#      - 'microservice-users/**'
  pull_request:
    branches:
      - main
#    paths:
#      - 'microservice-users/**'
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Change working directory
        run: cd /microservice-users
      - name: Install dependencies
        run: npm install
      - name: Test
        run: npm run test:e2e-cov
