name: Deploy Users Service
on:
  push:
    branches:
      - main
#    paths:
#      - 'microservice-users/**'
  pull_request:
    branches:
      - main
#    paths:
#      - 'microservice-users/**'
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      DB_TYPE: sqlite
      DB_DATABASE: mydatabase.sqlite
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          cd microservice-users
          npm install
      - name: Test
        run: |
          cd microservice-users
          npm run test:e2e-cov
  deploy:
    needs:
      - test
    name: Deploy
    uses: ./.github/workflows/deploy-microservice-workflow.yaml
    with:
      project_id: ${{ secrets.GCP_PROJECT_ID }}
      service: microservice-users
      region: us-central1
      source: microservice-users
      vif_provider: ${{ secrets.GCP_VIF_PROVIDER }}
      vif_service_account: ${{ secrets.GCP_VIF_SERVICE_ACCOUNT }}