name: Deploy Users Service
on:
  push:
    branches:
      - main
#    paths:
#      - 'microservice-users/**'
  pull_request:
    branches:
      - main
#    paths:
#      - 'microservice-users/**'
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      DB_TYPE: sqlite
      DB_DATABASE: mydatabase.sqlite
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          cd microservice-users
          npm install
      - name: Test
        run: |
          cd microservice-users
          npm run test:e2e-cov
      - name: call my internal workflow
        uses: ./.github/workflows/my-internal-workflow